import sys
sys.path.insert(0, "C:/Users/em8ee/OneDrive/Documents/cloudofficeprint-python")
import cloudofficeprint as cop

# Create main data collection
collection = cop.elements.ElementCollection()

# Add table of contents
toc = cop.elements.TableOfContents(
    name="toc_demo",
    title="Table of Contents - Generated by AOP",
    depth=2,
    tab_leader="hyphen"
)
collection.add(toc)

# Add customer data 
customers = [
    {
        "cust_f_name": "John",
        "cust_l_name": "Dulles",
        "city": "Sterling",
        "addr_1": "45020 Aviation Drive",
        "state": "VA",
        "email": "john.dulles@email.com",
        "phone_number_1": "703-555-2143",
        "phone_number_2": "703-555-8967",
        "url": "http://www.johndulles.com"
    },
    
    {   
        "cust_f_name": "Fiorello",
        "cust_l_name": "LaGuardia",
        "city": "Flushing",
        "addr_1": "Hangar Center",
        "addr_2": "Third Floor",
        "state": "NY",
        "phone_number_1": "212-555-3923"
    },
    {
        "cust_f_name": "Albert",
        "cust_l_name": "Lambert",
        "city": "St. Louis",
        "addr_1": "10701 Lambert International Blvd.",
        "state": "MO",
        "phone_number_1": "314-555-4022"

    }

    
]

customer_collections = []
for customer in customers:
    cust = cop.elements.ElementCollection()
    for key, value in customer.items():
        cust.add(cop.elements.Property(key, value))
    customer_collections.append(cust)

# customers to main collection 
customers_loop = cop.elements.ForEach("cust_list", customer_collections)
collection.add(customers_loop)

# Add the HTML content 
html_content = """
<h1>Heading 1 from html</h1>
<h2>Heading 2 from html</h2>
<h3>Heading 3 from html</h3>
AOP also handles the headings from html
"""
collection.add(cop.elements.Html(
    name="sample_html",
    value=html_content,
    custom_table_style=None,
    unordered_list_style=None,
    ordered_list_style=None,
    use_tag_style=True,
    ignore_cell_margin=None,
    ignore_empty_p=None
))

# Server configuration
server = cop.config.Server(
    "http://localhost:8010/",
    cop.config.ServerConfig(api_key="YOUR_API_KEY")
)

# Load template 
template = cop.Resource.from_local_file("./data/toc_temp.docx")

# Create and execute print job
printjob = cop.PrintJob(
    data=collection,
    server=server,
    template=template
)

# Save output
response = printjob.execute()
response.to_file("./output/output")